### ISSUE TITLE
custom widgets throws exception when no settings page is included

### ISSUE THREAD

**Issue by jccartwright** [Esri/arcgis-experience-builder-sdk-resources#171]
Custom widgets, e.g. [demo-function](https://github.com/Esri/arcgis-experience-builder-sdk-resources/tree/master/widgets/demo-function) throw an exception like the one below when a settings page is not included.

```
Could not load worker TypeError: e.split is not a function
    at ace.define.t.moduleUrl (json-editor-setting.js:2:20615)
    at ace.define.$createWorkerFromOldConfig (json-editor-setting.js:2:397438)
    at new l (json-editor-setting.js:2:397013)
    at u.createWorker (json-editor-setting.js:2:438662)
    at e.$startWorker (json-editor-setting.js:2:173014)
    at e.$onChangeMode (json-editor-setting.js:2:172398)
    at e.<anonymous> (json-editor-setting.js:2:172141)
    at l (json-editor-setting.js:2:21211)
    at ace.define.t.loadModule (json-editor-setting.js:2:21821)
    at e.setMode (json-editor-setting.js:2:171956)
```

**Comment by qlqllu** [comment]
@jccartwright Thanks for reporting this. When a widget does not have a setting page, a JSON editor will be shown to edit the config. This console error does not break any function. However, we fixed this by adding a setting page.
