### ISSUE TITLE
ArcGIS Experience Builder widget with ModalHeader component fails to run Jest tests

### ISSUE THREAD

**Issue by Matt-at-Hyland** [Esri/arcgis-experience-builder-sdk-resources#182]
Cannot add the `ModalHeader` component from the `jimu-ui` package and then be able to write tests.  

For example, if this is added to the simple-widget.test.tsx file:
```
import { Modal, ModalHeader } from 'jimu-ui'
...
render(<Modal isOpen={true}><ModalHeader></ModalHeader></Modal>);
```

This error is thrown:
```
 FAIL  your-extensions/widgets/simple/tests/simple-widget.test.tsx
  ● test simple widget › simple test

    TypeError: Cannot read properties of undefined (reading 'toLowerCase')

      44 |         .button-separator {
      45 |           height: 18px;
    > 46 |           border-right-width: 1px;
         |                                                                                     ^
      47 |           border-right-style: solid;
      48 |           border-right-color: ${e.colors.palette.light[700]};
      49 |         }

      at Mf (dist/jimu-core/index.js:46:367508)
      at sh (dist/jimu-core/index.js:46:377130)
      at yl.render (dist/jimu-ui/index.js:3113:8374)
      at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:19752:31)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:19698:24)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21611:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)
      at recoverFromConcurrentError (node_modules/react-dom/cjs/react-dom.development.js:25850:20)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26096:20)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26959:3)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:26)
      at render (node_modules/@testing-library/react/dist/pure.js:247:10)
      at render (jimu-for-test/lib/test-utils.tsx:19:17)
      at jimu-for-test/lib/test-utils.tsx:218:65
      at Object.<anonymous> (your-extensions/widgets/simple/tests/simple-widget.test.tsx:10:5)
```

**Comment by ming8525** [comment]
Hi @Matt-at-Hyland, the `ModalHeader` component uses the `i8n.getIntl` method in `jimu-core`, you can mock it like this to solve this error

```ts
jest.mock('jimu-core', () => {
  return {
    ...jest.requireActual('jimu-core'),
    i18n: {
      ...jest.requireActual('jimu-core').i18n,
      getIntl: jest.fn().mockReturnValue({
        formatMessage: (obj: { id: string }): string => obj.id
      })
    }
  }
})
```

**Comment by Matt-at-Hyland** [comment]
That did the trick.  Thanks!
Would have like to have seen this on this page: https://developers.arcgis.com/experience-builder/guide/unit-testing/

**Comment by ming8525** [comment]
Hi @Matt-at-Hyland, Thank you for your feedback. We have optimized the interface of testing utils. In the next version, you can set the first parameter of `widgetRender` to "true" to complete the state initialization, so you won't need to mock `intl` separately.
